// Carga horária por disciplina, conforme "7-MATRIZ CURRICULAR DO CFO 20
// MESES.xlsx" (confirmada pelo usuário como válida para o 23º e 24º CFO).
// Toda chave aqui bate 1:1 com uma entrada de MATERIAS_CFO1/2/3
// (src/config/materiasCfo1.ts, materiasCfo2.ts, materiasCfo3.ts) — inclui a
// migração já documentada de "Natação" do CFO II pro CFO III.
export const CARGA_HORARIA_CFO1: Record<string, number> = {
  "Sistema de Segurança Pública no Brasil": 30,
  "História da Policia Militar": 30,
  "Geopolítica de Mato Grosso": 30,
  "Policia Comunitária": 30,
  "Legislação Policial Militar I": 40,
  "Direitos humanos": 30,
  "Medicina Legal": 30,
  "Direito Processual Penal Militar I": 40,
  "Direito Penal Militar I": 40,
  "Direito Administrativo Disciplinar Militar I": 40,
  "Legislação Penal Extravagante I": 30,
  "Direito Ambiental": 30,
  "Redação Oficial Aplicada": 30,
  "Educação Física Policial Militar I": 30,
  "Defesa Pessoal I": 30,
  "Educação Financeira": 30,
  "Libras": 30,
  "Metodologia Científica / Pesquisa": 30,
  "Cerimonial e Protocolo": 30,
  "Comunicação Operacional/Telecomunicações": 30,
  "Armamento de Fogo, Munição e Explosivos": 45,
  "Bombeiro Militar e Defesa Civil": 30,
  "Cultura e Cotidiano Policial Militar": 60,
  "Teoria de Policia": 30,
  "Didática: Sistema de Ensino": 40,
  "Técnicas Gerais de Policiamento I": 45,
  "POP I": 60,
  "Defesa Territorial I": 30,
  "Hipologia e Equitação": 30,
  "Administração Pública Gerencial": 30,
  "APH": 30,
  "Tiro Policial": 90,
};

export const CARGA_HORARIA_CFO2: Record<string, number> = {
  "Criminologia Aplicada a Segurança Pública": 30,
  "Sociologia do Crime e da Violência": 30,
  "Direito Penal Militar II": 30,
  "Direito Administrativo Aplicado a Seg. Publica.": 30,
  "Direito Processual Penal Militar II": 30,
  "Legislação Policial Militar II": 30,
  "Direito Administrativo Disciplinar Militar II": 30,
  "Legislação Penal Extravagante II": 30,
  "Educação Física Policial Militar II": 30,
  "Defesa Pessoal II": 30,
  "Gestão de Informação – Inteligência": 30,
  "Saúde Segurança aplicada ao Trabalho": 30,
  "Marketing Institucional": 30,
  "Metodologia Científica/Projeto de Pesquisa": 30,
  "Geoprocessamento e Análise Criminal": 30,
  "Emergência e Traumas": 30,
  "Cultura e Cotidiano Policial Militar II": 45,
  "Técnicas Gerais de Policiamento II": 45,
  "POP II": 60,
  "Criminalística": 30,
  "Defesa Territorial II": 30,
  "Policiamento Montado": 30,
  "Uso diferenciado da Força": 30,
  "Gestão de Pessoas": 30,
  "Termo Circunstanciado de Ocorrência": 30,
  "Sistemas Informatizados": 30,
  "Tiro Policial": 90,
};

export const CARGA_HORARIA_CFO3: Record<string, number> = {
  "Licitação de Contrato e Aquisição": 45,
  "Direito Penal Militar III": 30,
  "Direito Processual Penal Militar III": 30,
  "Legislação Policial Militar III": 30,
  "Direito Administrativo Disciplinar Militar III": 30,
  "Gerenciamento de Crises e Eventos Críticos": 45,
  "Educação Física Policial Militar III": 30,
  "Controle e submissão": 30,
  "Artigo Científico": 30,
  "Seminário de Trabalho Científico-Workshop de Banca de Defesa do TCC": 45,
  "Cultura e Cotidiano Policial Militar III": 30,
  "EPP – Estagio de Patrulhamento Tático": 30,
  "Técnicas Gerais de Policiamento III": 30,
  "POP III": 60,
  "Segurança Física de Instalações e Dignatários": 45,
  "Defesa Territorial III": 30,
  "Policiamento Ambiental": 45,
  "Policiamento de Trânsito": 45,
  "Policiamento de Grandes eventos": 30,
  "Técnicas não letais": 30,
  "Gestão de Recursos Públicos": 30,
  "Gestão Pública por Resultados": 30,
  "Gestão de Logística e Patrimônio": 30,
  "Tiro Policial": 90,
  "Termo Circunstanciado de Ocorrência": 30,
  "Natação": 30,
};
