// Lista oficial de disciplinas do CFO I, conforme Matriz Curricular do CFO (20 meses).
// Usada para: (1) contar "matérias avaliadas / total" e (2) popular o seletor de
// matéria no lançamento de notas do admin.
export const MATERIAS_CFO1: string[] = [
  "Sistema de Segurança Pública no Brasil",
  "História da Policia Militar",
  "Geopolítica de Mato Grosso",
  "Policia Comunitária",
  "Legislação Policial Militar I",
  "Direitos humanos",
  "Medicina Legal",
  "Direito Processual Penal Militar I",
  "Direito Penal Militar I",
  "Direito Administrativo Disciplinar Militar I",
  "Legislação Penal Extravagante I",
  "Direito Ambiental",
  "Redação Oficial Aplicada",
  "Educação Física Policial Militar I",
  "Defesa Pessoal I",
  "Educação Financeira",
  "Libras",
  "Metodologia Científica / Pesquisa",
  "Cerimonial e Protocolo",
  "Comunicação Operacional/Telecomunicações",
  "Armamento de Fogo, Munição e Explosivos",
  "Bombeiro Militar e Defesa Civil",
  "Cultura e Cotidiano Policial Militar",
  "Teoria de Policia",
  "Didática: Sistema de Ensino",
  "Técnicas Gerais de Policiamento I",
  "POP I",
  "Defesa Territorial I",
  "Hipologia e Equitação",
  "Administração Pública Gerencial",
  "APH",
  "Tiro Policial",
];
